### PR TITLE
Adding Support for Glucose 4.2.1

### PR DESCRIPTION
**Pull request by marino-mrc**
Hello,
my PR is for adding support to Glucose 4.2.1
Also, I improved a bit the "genpatches.py" script.

Thanks,
Marco

### CODE REVIEW

**Comment by alexeyignatiev** [comment]
Hi Marco,

The PR seems to [fail to compile](https://ci.appveyor.com/project/pysathq/pysat/builds/47471351) on Windows. Can you check what is wrong? As a general rule of thumb, the patch should be as close to the other versions of Glucose patches as possible. This includes the compiler `c++` and the corresponding compiler options. Also, the existing patches (including the one for lingeling) should not be modified.

Best,
Alexey

**Comment by marino-mrc** [comment]
Hi Alexey, I'm working on this and it will be fixed soon.
But I have one question:
can you clarify the meaning of
`vec<bool>           assump;           // Declares if a variable is an assumption variable or not.`

in the Solver class? I'm checking the code you added in Glucose 4.1 and I noticed this protected var. 
The point is: the variable is used only in the following function
`inline bool isSelector(Var v) { return (incremental && assump[v]); }`

and it's never assigned. 

Furthermore, we have the following on both Glucose 4.1 and 4.2.1:
`vec<Lit>            assumptions;      // Current set of assumptions provided to solve by the user.`

So, why do we need another assump variable? I wonder if I really need to include it in the code of Glucose 4.2.1

Thanks,
Marco

**Comment by alexeyignatiev** [comment]
Hi Marco,

The vector `assump` is used as a characteristic vector mapping variables to Boolean flags to be used as a quick check  whether specific variables are currently used as assumption literals or not. Note that this is different from the list of `assumptions`, which can be sorted arbitrarily. The functionality was introduced as an incrementally improvement feature of Glucose 3 and then adapted in Glucose 4, published in:

G. Audemard, J.-M. Lagniez, L. Simon: _Improving Glucose for Incremental SAT Solving with Assumptions: Application to MUS Extraction_. SAT 2013: 309-317

Note that it is used in several places in `core/Solver.cc`. I hope this helps.

Alexey

**Comment by marino-mrc** [comment]
Hello Alexey, here is an update about my work:

- I fixed almost everything and now the only job that fails is for Python 3.7 (64-bit). I'm not sure about the error: it seems a temporary error and I cannot reproduce it. It's related to the appveyor/instdep.py script. Please, can you take a look at the error? Let me know if you have any ideas or if you can simply re-run the job

- About the "assump" variable: I'm sorry, I have to disagree. I checked the following archives:
1. http://www.labri.fr/perso/lsimon/downloads/softwares/glucose-3.0.tgz  (Glucose 3.0)
2. http://www.labri.fr/perso/lsimon/downloads/softwares/glucose-syrup-4.1.tgz (Glucose 4.1)
3. https://github.com/audemard/glucose/archive/refs/tags/4.2.1.tar.gz (Glucose 4.2.1)
and I cannot find any evidence of the use of the "assump" protected class variable. Furthermore, you add it in the patch file and this confirms that the variable doesn't exist in the original code.
As a side point, please note that the "assump" variable used many times in the Solver.cc file is a local variable inside some functions (declared in the prototype of those functions) but it's not the protected class variable I mentioned in my previous comment.

At the moment, the Jobs are working (except for Python 3.7) but I don't use the "assump" variable in Glucose 4.2.1 and I left the code in the "isSelector" function as originally provided in Glucose 4.2.1

Thanks,
Marco

**Comment by alexeyignatiev** [comment]
Hi Marco,

Well, not sure why you question my comments - I don't seem to have any incentive to lie here. The `assump` variable was introduced by myself in order to make the aforementioned incrementality feature of Glucose 3 _actually be usable_ with arbitrary assumption variables and the possibility to extend the list of variables in use.

If you check the original code of Glucose 3, it assumes a variable to be an assumption variable if `v>nbVarsInitialFormula`. This immediately breaks down if I extend the list of non-assumption variables in any practical setting when the list of variables grows after making SAT calls, i.e. in MaxSAT where the formula is updated all the time. So I had to change the original code and use a characteristic vector, such that the value `assump[v]` is true whenever the variable is marked as assumption variable and it is false otherwise.

This means you will need to update your code accordingly. You don't have to keep it protected if you want to make it private or public - it does not change the semantics of the variable. The important point here is that the set of variables should be extendable such that non-assumption variables may after assumption variables and the other way around.

Best,
Alexey

**Comment by marino-mrc** [comment]
Hi Alexey, thanks for your explanation. I'm sorry but I had to ask because I need to fully understand a patch before porting it in Glucose 4.2.1 otherwise I could make mistakes due to my lack of knowledge on that specific topic.

Now I ported everything and it seems Glucose 4.2.1 is fully supported in my fork of pysat.
There are 2 open problems:

- the checks randomly fail due to an error in appveyor/instdep.py. I think this is due to a problem with the HTTP request for downloading a JSON object containing dependencies in that file. As I said, the problem happens randomly and is not strictly related to pysat. Please, take a look at it and let me know if you have any ideas.
- I'm not sure how I can remove the .patch files related to other solvers I erroneously added to my PR. In my local repo, I removed the files but it seems I can't do the same through the git command line. I noticed that in the "Files changed" menu on Git Hub, there is a "Delete file" for each file. Can I use it for removing all unneeded patch files?

Thank you.
Regards,
Marco

**Comment by alexeyignatiev** [comment]
Hi Marco,

Sure, I understand the rationale of your questions. I guess I should have explained better what is implemented and why.

As for the compilation issue with AppVeyor, the thing is it should not happen. In fact, AppVeyor provides me with the binary wheels for Windows, which means failing to build any one of those is a problem because we won't have the corresponding binary wheels.

I think the issue may arise because the source code of Glucose 4.2.1 is not kept in `solvers/`. Can you download it, save there as `solvers/glucose421.tar.gz` together with the other archives, and push again?

Best,
Alexey

**Comment by marino-mrc** [comment]
Hello Alexey,
now checks are working ( I had to patch the instdep.py file)

I think there is one more open problem: unneeded patch files. Please let me know if you have any idea on how to remove them from the PR.

Thank you.
Regards,
Marco

**Comment by alexeyignatiev** [comment]
Thanks, Marco. I have to say that commenting out important lines in `instdep.py` isn't really a fix. :) I will have to put them back.

**Pull request merged**
